FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/ws-backend ./apps/ws-backend

RUN bun install
RUN bun run db:generate
RUN bun run build

EXPOSE 8080

CMD [ "bun", "run", "start:ws-backend" ]